defaults:
  - _self_
  - ds: rugd
  - model: deeplabv3_resnet50

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 0.0001

train:
  batch_size: 2
  max_epochs: 100
  num_workers: 4


